# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ece52f5fe205e64993db9ff18e1e381ac02f8ebc4ab2d1970e5f98ca33bc966616032f45009ccf0a43caa222b61934d490dc101d58301707fa995fb9fd7a0bb1

test:
  secret_key_base: 500a1e9d50fd3e274a2bb405c47893ef770b8060a80da6d213ee256b511ca2c15456308cfba521e16bc69fb668b1e59add988c20d7e2b87c15a70292e858a191

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
